[2022-02-02 18:07:41,161] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2019-02-01T00:00:00+00:00 [queued]>
[2022-02-02 18:07:41,187] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2019-02-01T00:00:00+00:00 [queued]>
[2022-02-02 18:07:41,189] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-02 18:07:41,190] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-02 18:07:41,192] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-02 18:07:41,219] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2019-02-01 00:00:00+00:00
[2022-02-02 18:07:41,238] {standard_task_runner.py:52} INFO - Started process 8353 to run task
[2022-02-02 18:07:41,259] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ex_1_data_ingestion_gcs_dag_v3', 'local_to_gcs_task', 'scheduled__2019-02-01T00:00:00+00:00', '--job-id', '309', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_hw_1_ex.py', '--cfg-path', '/tmp/tmpesm06a8f', '--error-file', '/tmp/tmpfq28g97_']
[2022-02-02 18:07:41,271] {standard_task_runner.py:77} INFO - Job 309: Subtask local_to_gcs_task
[2022-02-02 18:07:41,396] {logging_mixin.py:109} INFO - Running <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2019-02-01T00:00:00+00:00 [running]> on host 700aeb16bae0
[2022-02-02 18:07:41,474] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-02 18:07:41,523] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ex_1_data_ingestion_gcs_dag_v3
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2019-02-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-02-01T00:00:00+00:00
[2022-02-02 18:07:51,710] {python.py:175} INFO - Done. Returned value was: None
[2022-02-02 18:07:51,727] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ex_1_data_ingestion_gcs_dag_v3, task_id=local_to_gcs_task, execution_date=20190201T000000, start_date=20220202T180741, end_date=20220202T180751
[2022-02-02 18:07:51,759] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-02 18:07:51,799] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-02-10 12:48:44,893] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2019-02-01T00:00:00+00:00 [queued]>
[2022-02-10 12:48:44,908] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2019-02-01T00:00:00+00:00 [queued]>
[2022-02-10 12:48:44,910] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-10 12:48:44,911] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-10 12:48:44,912] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-10 12:48:44,926] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2019-02-01 00:00:00+00:00
[2022-02-10 12:48:44,932] {standard_task_runner.py:52} INFO - Started process 730 to run task
[2022-02-10 12:48:44,937] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ex_1_data_ingestion_gcs_dag_v3', 'local_to_gcs_task', 'scheduled__2019-02-01T00:00:00+00:00', '--job-id', '665', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_hw_1_ex.py', '--cfg-path', '/tmp/tmp2pdcgqz_', '--error-file', '/tmp/tmpm6o81sze']
[2022-02-10 12:48:44,939] {standard_task_runner.py:77} INFO - Job 665: Subtask local_to_gcs_task
[2022-02-10 12:48:45,015] {logging_mixin.py:109} INFO - Running <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2019-02-01T00:00:00+00:00 [running]> on host e30f201fae61
[2022-02-10 12:48:45,068] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-10 12:48:45,101] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ex_1_data_ingestion_gcs_dag_v3
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2019-02-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-02-01T00:00:00+00:00
[2022-02-10 12:48:59,066] {python.py:175} INFO - Done. Returned value was: None
[2022-02-10 12:48:59,090] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ex_1_data_ingestion_gcs_dag_v3, task_id=local_to_gcs_task, execution_date=20190201T000000, start_date=20220210T124844, end_date=20220210T124859
[2022-02-10 12:48:59,128] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-10 12:48:59,165] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-02-10 15:31:35,155] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2019-02-01T00:00:00+00:00 [queued]>
[2022-02-10 15:31:35,180] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2019-02-01T00:00:00+00:00 [queued]>
[2022-02-10 15:31:35,181] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-10 15:31:35,182] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-10 15:31:35,184] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-10 15:31:35,203] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2019-02-01 00:00:00+00:00
[2022-02-10 15:31:35,232] {standard_task_runner.py:52} INFO - Started process 202 to run task
[2022-02-10 15:31:35,236] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ex_1_data_ingestion_gcs_dag_v3', 'local_to_gcs_task', 'scheduled__2019-02-01T00:00:00+00:00', '--job-id', '786', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_hw_1_ex.py', '--cfg-path', '/tmp/tmpoxr5d7oa', '--error-file', '/tmp/tmp4_cmcxgp']
[2022-02-10 15:31:35,242] {standard_task_runner.py:77} INFO - Job 786: Subtask local_to_gcs_task
[2022-02-10 15:31:35,376] {logging_mixin.py:109} INFO - Running <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2019-02-01T00:00:00+00:00 [running]> on host 276a0ad90304
[2022-02-10 15:31:35,449] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-10 15:31:35,488] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ex_1_data_ingestion_gcs_dag_v3
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2019-02-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-02-01T00:00:00+00:00
[2022-02-10 15:31:48,350] {python.py:175} INFO - Done. Returned value was: None
[2022-02-10 15:31:48,399] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ex_1_data_ingestion_gcs_dag_v3, task_id=local_to_gcs_task, execution_date=20190201T000000, start_date=20220210T153135, end_date=20220210T153148
[2022-02-10 15:31:48,447] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-10 15:31:48,483] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-02-10 16:31:17,176] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2019-02-01T00:00:00+00:00 [queued]>
[2022-02-10 16:31:17,203] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2019-02-01T00:00:00+00:00 [queued]>
[2022-02-10 16:31:17,204] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-10 16:31:17,206] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-10 16:31:17,207] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-10 16:31:17,226] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2019-02-01 00:00:00+00:00
[2022-02-10 16:31:17,235] {standard_task_runner.py:52} INFO - Started process 229 to run task
[2022-02-10 16:31:17,241] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ex_1_data_ingestion_gcs_dag_v3', 'local_to_gcs_task', 'scheduled__2019-02-01T00:00:00+00:00', '--job-id', '930', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_hw_1_ex.py', '--cfg-path', '/tmp/tmpnhduw0si', '--error-file', '/tmp/tmpxqpw32ts']
[2022-02-10 16:31:17,243] {standard_task_runner.py:77} INFO - Job 930: Subtask local_to_gcs_task
[2022-02-10 16:31:17,363] {logging_mixin.py:109} INFO - Running <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2019-02-01T00:00:00+00:00 [running]> on host 106a34111faf
[2022-02-10 16:31:17,443] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-10 16:31:17,503] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ex_1_data_ingestion_gcs_dag_v3
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2019-02-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-02-01T00:00:00+00:00
[2022-02-10 16:32:29,803] {python.py:175} INFO - Done. Returned value was: None
[2022-02-10 16:32:29,851] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ex_1_data_ingestion_gcs_dag_v3, task_id=local_to_gcs_task, execution_date=20190201T000000, start_date=20220210T163117, end_date=20220210T163229
[2022-02-10 16:32:29,937] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-10 16:32:30,018] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
