[2022-02-02 18:51:32,132] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2020-04-01T00:00:00+00:00 [queued]>
[2022-02-02 18:51:32,149] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2020-04-01T00:00:00+00:00 [queued]>
[2022-02-02 18:51:32,150] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-02 18:51:32,150] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-02 18:51:32,151] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-02 18:51:32,164] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2020-04-01 00:00:00+00:00
[2022-02-02 18:51:32,171] {standard_task_runner.py:52} INFO - Started process 10610 to run task
[2022-02-02 18:51:32,176] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ex_1_data_ingestion_gcs_dag_v3', 'local_to_gcs_task', 'scheduled__2020-04-01T00:00:00+00:00', '--job-id', '349', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_hw_1_ex.py', '--cfg-path', '/tmp/tmpnyx995y3', '--error-file', '/tmp/tmprrqnsk1m']
[2022-02-02 18:51:32,177] {standard_task_runner.py:77} INFO - Job 349: Subtask local_to_gcs_task
[2022-02-02 18:51:32,252] {logging_mixin.py:109} INFO - Running <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2020-04-01T00:00:00+00:00 [running]> on host 700aeb16bae0
[2022-02-02 18:51:32,300] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-02 18:51:32,329] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ex_1_data_ingestion_gcs_dag_v3
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2020-04-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-04-01T00:00:00+00:00
[2022-02-02 18:51:35,044] {python.py:175} INFO - Done. Returned value was: None
[2022-02-02 18:51:35,058] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ex_1_data_ingestion_gcs_dag_v3, task_id=local_to_gcs_task, execution_date=20200401T000000, start_date=20220202T185132, end_date=20220202T185135
[2022-02-02 18:51:35,112] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-02 18:51:35,146] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-02-10 13:22:11,126] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2020-04-01T00:00:00+00:00 [queued]>
[2022-02-10 13:22:11,143] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2020-04-01T00:00:00+00:00 [queued]>
[2022-02-10 13:22:11,144] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-10 13:22:11,145] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-10 13:22:11,146] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-10 13:22:11,159] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2020-04-01 00:00:00+00:00
[2022-02-10 13:22:11,166] {standard_task_runner.py:52} INFO - Started process 2503 to run task
[2022-02-10 13:22:11,172] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ex_1_data_ingestion_gcs_dag_v3', 'local_to_gcs_task', 'scheduled__2020-04-01T00:00:00+00:00', '--job-id', '707', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_hw_1_ex.py', '--cfg-path', '/tmp/tmpr8sdzuoy', '--error-file', '/tmp/tmpifhn_s2s']
[2022-02-10 13:22:11,175] {standard_task_runner.py:77} INFO - Job 707: Subtask local_to_gcs_task
[2022-02-10 13:22:11,251] {logging_mixin.py:109} INFO - Running <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2020-04-01T00:00:00+00:00 [running]> on host e30f201fae61
[2022-02-10 13:22:11,295] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-10 13:22:11,323] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ex_1_data_ingestion_gcs_dag_v3
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2020-04-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-04-01T00:00:00+00:00
[2022-02-10 13:22:12,627] {python.py:175} INFO - Done. Returned value was: None
[2022-02-10 13:22:12,658] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ex_1_data_ingestion_gcs_dag_v3, task_id=local_to_gcs_task, execution_date=20200401T000000, start_date=20220210T132211, end_date=20220210T132212
[2022-02-10 13:22:12,718] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-10 13:22:12,759] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-02-10 15:40:01,013] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2020-04-01T00:00:00+00:00 [queued]>
[2022-02-10 15:40:01,074] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2020-04-01T00:00:00+00:00 [queued]>
[2022-02-10 15:40:01,080] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-10 15:40:01,082] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-10 15:40:01,083] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-10 15:40:01,131] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2020-04-01 00:00:00+00:00
[2022-02-10 15:40:01,188] {standard_task_runner.py:52} INFO - Started process 805 to run task
[2022-02-10 15:40:01,229] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ex_1_data_ingestion_gcs_dag_v3', 'local_to_gcs_task', 'scheduled__2020-04-01T00:00:00+00:00', '--job-id', '826', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_hw_1_ex.py', '--cfg-path', '/tmp/tmpen8ooo0j', '--error-file', '/tmp/tmpdkodtjdm']
[2022-02-10 15:40:01,233] {standard_task_runner.py:77} INFO - Job 826: Subtask local_to_gcs_task
[2022-02-10 15:40:01,419] {logging_mixin.py:109} INFO - Running <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2020-04-01T00:00:00+00:00 [running]> on host 276a0ad90304
[2022-02-10 15:40:01,526] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-10 15:40:01,583] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ex_1_data_ingestion_gcs_dag_v3
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2020-04-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-04-01T00:00:00+00:00
[2022-02-10 15:40:03,132] {python.py:175} INFO - Done. Returned value was: None
[2022-02-10 15:40:03,158] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ex_1_data_ingestion_gcs_dag_v3, task_id=local_to_gcs_task, execution_date=20200401T000000, start_date=20220210T154001, end_date=20220210T154003
[2022-02-10 15:40:03,208] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-10 15:40:03,277] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-02-10 16:40:51,436] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2020-04-01T00:00:00+00:00 [queued]>
[2022-02-10 16:40:51,492] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2020-04-01T00:00:00+00:00 [queued]>
[2022-02-10 16:40:51,498] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-10 16:40:51,501] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-10 16:40:51,503] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-10 16:40:51,547] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2020-04-01 00:00:00+00:00
[2022-02-10 16:40:51,568] {standard_task_runner.py:52} INFO - Started process 728 to run task
[2022-02-10 16:40:51,584] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ex_1_data_ingestion_gcs_dag_v3', 'local_to_gcs_task', 'scheduled__2020-04-01T00:00:00+00:00', '--job-id', '957', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_hw_1_ex.py', '--cfg-path', '/tmp/tmp78nqo1mh', '--error-file', '/tmp/tmp56thxz6m']
[2022-02-10 16:40:51,612] {standard_task_runner.py:77} INFO - Job 957: Subtask local_to_gcs_task
[2022-02-10 16:40:51,840] {logging_mixin.py:109} INFO - Running <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2020-04-01T00:00:00+00:00 [running]> on host 106a34111faf
[2022-02-10 16:40:51,954] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-10 16:40:52,053] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ex_1_data_ingestion_gcs_dag_v3
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2020-04-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-04-01T00:00:00+00:00
[2022-02-10 16:40:56,862] {python.py:175} INFO - Done. Returned value was: None
[2022-02-10 16:40:56,980] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ex_1_data_ingestion_gcs_dag_v3, task_id=local_to_gcs_task, execution_date=20200401T000000, start_date=20220210T164051, end_date=20220210T164056
[2022-02-10 16:40:57,208] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-10 16:40:57,325] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
