[2022-02-02 18:53:50,250] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2020-06-01T00:00:00+00:00 [queued]>
[2022-02-02 18:53:50,266] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2020-06-01T00:00:00+00:00 [queued]>
[2022-02-02 18:53:50,268] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-02 18:53:50,269] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-02 18:53:50,270] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-02 18:53:50,286] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2020-06-01 00:00:00+00:00
[2022-02-02 18:53:50,294] {standard_task_runner.py:52} INFO - Started process 10756 to run task
[2022-02-02 18:53:50,299] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ex_1_data_ingestion_gcs_dag_v3', 'local_to_gcs_task', 'scheduled__2020-06-01T00:00:00+00:00', '--job-id', '355', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_hw_1_ex.py', '--cfg-path', '/tmp/tmp3gp9ur25', '--error-file', '/tmp/tmpm2_dxlrs']
[2022-02-02 18:53:50,301] {standard_task_runner.py:77} INFO - Job 355: Subtask local_to_gcs_task
[2022-02-02 18:53:50,377] {logging_mixin.py:109} INFO - Running <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2020-06-01T00:00:00+00:00 [running]> on host 700aeb16bae0
[2022-02-02 18:53:50,421] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-02 18:53:50,445] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ex_1_data_ingestion_gcs_dag_v3
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2020-06-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-06-01T00:00:00+00:00
[2022-02-02 18:53:52,377] {python.py:175} INFO - Done. Returned value was: None
[2022-02-02 18:53:52,393] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ex_1_data_ingestion_gcs_dag_v3, task_id=local_to_gcs_task, execution_date=20200601T000000, start_date=20220202T185350, end_date=20220202T185352
[2022-02-02 18:53:52,427] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-02 18:53:52,465] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-02-10 13:23:55,316] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2020-06-01T00:00:00+00:00 [queued]>
[2022-02-10 13:23:55,331] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2020-06-01T00:00:00+00:00 [queued]>
[2022-02-10 13:23:55,332] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-10 13:23:55,333] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-10 13:23:55,334] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-10 13:23:55,364] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2020-06-01 00:00:00+00:00
[2022-02-10 13:23:55,376] {standard_task_runner.py:52} INFO - Started process 2617 to run task
[2022-02-10 13:23:55,381] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ex_1_data_ingestion_gcs_dag_v3', 'local_to_gcs_task', 'scheduled__2020-06-01T00:00:00+00:00', '--job-id', '713', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_hw_1_ex.py', '--cfg-path', '/tmp/tmpc1zv6x3k', '--error-file', '/tmp/tmpmcqf9d92']
[2022-02-10 13:23:55,384] {standard_task_runner.py:77} INFO - Job 713: Subtask local_to_gcs_task
[2022-02-10 13:23:55,451] {logging_mixin.py:109} INFO - Running <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2020-06-01T00:00:00+00:00 [running]> on host e30f201fae61
[2022-02-10 13:23:55,492] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-10 13:23:55,516] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ex_1_data_ingestion_gcs_dag_v3
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2020-06-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-06-01T00:00:00+00:00
[2022-02-10 13:23:57,358] {python.py:175} INFO - Done. Returned value was: None
[2022-02-10 13:23:57,379] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ex_1_data_ingestion_gcs_dag_v3, task_id=local_to_gcs_task, execution_date=20200601T000000, start_date=20220210T132355, end_date=20220210T132357
[2022-02-10 13:23:57,441] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-10 13:23:57,476] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-02-10 15:40:25,313] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2020-06-01T00:00:00+00:00 [queued]>
[2022-02-10 15:40:25,331] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2020-06-01T00:00:00+00:00 [queued]>
[2022-02-10 15:40:25,332] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-10 15:40:25,334] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-10 15:40:25,335] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-10 15:40:25,353] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2020-06-01 00:00:00+00:00
[2022-02-10 15:40:25,366] {standard_task_runner.py:52} INFO - Started process 876 to run task
[2022-02-10 15:40:25,371] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ex_1_data_ingestion_gcs_dag_v3', 'local_to_gcs_task', 'scheduled__2020-06-01T00:00:00+00:00', '--job-id', '836', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_hw_1_ex.py', '--cfg-path', '/tmp/tmpogmghw3l', '--error-file', '/tmp/tmpufknysgb']
[2022-02-10 15:40:25,373] {standard_task_runner.py:77} INFO - Job 836: Subtask local_to_gcs_task
[2022-02-10 15:40:25,467] {logging_mixin.py:109} INFO - Running <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2020-06-01T00:00:00+00:00 [running]> on host 276a0ad90304
[2022-02-10 15:40:25,543] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-10 15:40:25,572] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ex_1_data_ingestion_gcs_dag_v3
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2020-06-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-06-01T00:00:00+00:00
[2022-02-10 15:40:28,718] {python.py:175} INFO - Done. Returned value was: None
[2022-02-10 15:40:28,747] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ex_1_data_ingestion_gcs_dag_v3, task_id=local_to_gcs_task, execution_date=20200601T000000, start_date=20220210T154025, end_date=20220210T154028
[2022-02-10 15:40:28,827] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-10 15:40:28,895] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-02-10 16:41:20,099] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2020-06-01T00:00:00+00:00 [queued]>
[2022-02-10 16:41:20,131] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2020-06-01T00:00:00+00:00 [queued]>
[2022-02-10 16:41:20,132] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-10 16:41:20,134] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-10 16:41:20,136] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-10 16:41:20,156] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2020-06-01 00:00:00+00:00
[2022-02-10 16:41:20,162] {standard_task_runner.py:52} INFO - Started process 759 to run task
[2022-02-10 16:41:20,169] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ex_1_data_ingestion_gcs_dag_v3', 'local_to_gcs_task', 'scheduled__2020-06-01T00:00:00+00:00', '--job-id', '961', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_hw_1_ex.py', '--cfg-path', '/tmp/tmp7vv5xni4', '--error-file', '/tmp/tmpx75pwct2']
[2022-02-10 16:41:20,173] {standard_task_runner.py:77} INFO - Job 961: Subtask local_to_gcs_task
[2022-02-10 16:41:20,357] {logging_mixin.py:109} INFO - Running <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2020-06-01T00:00:00+00:00 [running]> on host 106a34111faf
[2022-02-10 16:41:20,456] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-10 16:41:20,495] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ex_1_data_ingestion_gcs_dag_v3
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2020-06-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-06-01T00:00:00+00:00
[2022-02-10 16:41:24,950] {python.py:175} INFO - Done. Returned value was: None
[2022-02-10 16:41:24,971] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ex_1_data_ingestion_gcs_dag_v3, task_id=local_to_gcs_task, execution_date=20200601T000000, start_date=20220210T164120, end_date=20220210T164124
[2022-02-10 16:41:25,009] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-10 16:41:25,094] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
