[2022-02-02 18:12:03,626] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2019-03-01T00:00:00+00:00 [queued]>
[2022-02-02 18:12:03,638] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2019-03-01T00:00:00+00:00 [queued]>
[2022-02-02 18:12:03,639] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-02 18:12:03,640] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-02 18:12:03,641] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-02 18:12:03,656] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2019-03-01 00:00:00+00:00
[2022-02-02 18:12:03,666] {standard_task_runner.py:52} INFO - Started process 8562 to run task
[2022-02-02 18:12:03,676] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ex_1_data_ingestion_gcs_dag_v3', 'local_to_gcs_task', 'scheduled__2019-03-01T00:00:00+00:00', '--job-id', '312', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_hw_1_ex.py', '--cfg-path', '/tmp/tmp_g75sixp', '--error-file', '/tmp/tmpvxl7dbv7']
[2022-02-02 18:12:03,678] {standard_task_runner.py:77} INFO - Job 312: Subtask local_to_gcs_task
[2022-02-02 18:12:03,760] {logging_mixin.py:109} INFO - Running <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2019-03-01T00:00:00+00:00 [running]> on host 700aeb16bae0
[2022-02-02 18:12:03,804] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-02 18:12:03,830] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ex_1_data_ingestion_gcs_dag_v3
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2019-03-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-03-01T00:00:00+00:00
[2022-02-02 18:12:28,252] {python.py:175} INFO - Done. Returned value was: None
[2022-02-02 18:12:28,267] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ex_1_data_ingestion_gcs_dag_v3, task_id=local_to_gcs_task, execution_date=20190301T000000, start_date=20220202T181203, end_date=20220202T181228
[2022-02-02 18:12:28,325] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-02 18:12:28,380] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-02-10 12:51:02,609] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2019-03-01T00:00:00+00:00 [queued]>
[2022-02-10 12:51:02,627] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2019-03-01T00:00:00+00:00 [queued]>
[2022-02-10 12:51:02,628] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-10 12:51:02,629] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-10 12:51:02,630] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-10 12:51:02,645] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2019-03-01 00:00:00+00:00
[2022-02-10 12:51:02,653] {standard_task_runner.py:52} INFO - Started process 847 to run task
[2022-02-10 12:51:02,659] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ex_1_data_ingestion_gcs_dag_v3', 'local_to_gcs_task', 'scheduled__2019-03-01T00:00:00+00:00', '--job-id', '668', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_hw_1_ex.py', '--cfg-path', '/tmp/tmphrbavk3x', '--error-file', '/tmp/tmpuiye8cml']
[2022-02-10 12:51:02,663] {standard_task_runner.py:77} INFO - Job 668: Subtask local_to_gcs_task
[2022-02-10 12:51:02,747] {logging_mixin.py:109} INFO - Running <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2019-03-01T00:00:00+00:00 [running]> on host e30f201fae61
[2022-02-10 12:51:02,807] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-10 12:51:02,846] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ex_1_data_ingestion_gcs_dag_v3
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2019-03-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-03-01T00:00:00+00:00
[2022-02-10 12:51:15,401] {python.py:175} INFO - Done. Returned value was: None
[2022-02-10 12:51:15,424] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ex_1_data_ingestion_gcs_dag_v3, task_id=local_to_gcs_task, execution_date=20190301T000000, start_date=20220210T125102, end_date=20220210T125115
[2022-02-10 12:51:15,491] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-10 12:51:15,540] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-02-10 15:33:05,772] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2019-03-01T00:00:00+00:00 [queued]>
[2022-02-10 15:33:05,795] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2019-03-01T00:00:00+00:00 [queued]>
[2022-02-10 15:33:05,796] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-10 15:33:05,798] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-10 15:33:05,800] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-10 15:33:05,822] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2019-03-01 00:00:00+00:00
[2022-02-10 15:33:05,836] {standard_task_runner.py:52} INFO - Started process 309 to run task
[2022-02-10 15:33:05,841] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ex_1_data_ingestion_gcs_dag_v3', 'local_to_gcs_task', 'scheduled__2019-03-01T00:00:00+00:00', '--job-id', '792', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_hw_1_ex.py', '--cfg-path', '/tmp/tmpjmspbkep', '--error-file', '/tmp/tmpt5ldr3sz']
[2022-02-10 15:33:05,846] {standard_task_runner.py:77} INFO - Job 792: Subtask local_to_gcs_task
[2022-02-10 15:33:05,961] {logging_mixin.py:109} INFO - Running <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2019-03-01T00:00:00+00:00 [running]> on host 276a0ad90304
[2022-02-10 15:33:06,040] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-10 15:33:06,085] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ex_1_data_ingestion_gcs_dag_v3
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2019-03-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-03-01T00:00:00+00:00
[2022-02-10 15:33:19,789] {python.py:175} INFO - Done. Returned value was: None
[2022-02-10 15:33:19,826] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ex_1_data_ingestion_gcs_dag_v3, task_id=local_to_gcs_task, execution_date=20190301T000000, start_date=20220210T153305, end_date=20220210T153319
[2022-02-10 15:33:19,891] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-10 15:33:19,925] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-02-10 16:31:47,757] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2019-03-01T00:00:00+00:00 [queued]>
[2022-02-10 16:31:47,816] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2019-03-01T00:00:00+00:00 [queued]>
[2022-02-10 16:31:47,820] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-10 16:31:47,823] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-10 16:31:47,825] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-10 16:31:47,877] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2019-03-01 00:00:00+00:00
[2022-02-10 16:31:47,892] {standard_task_runner.py:52} INFO - Started process 254 to run task
[2022-02-10 16:31:47,928] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ex_1_data_ingestion_gcs_dag_v3', 'local_to_gcs_task', 'scheduled__2019-03-01T00:00:00+00:00', '--job-id', '932', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_hw_1_ex.py', '--cfg-path', '/tmp/tmps1c6c2oi', '--error-file', '/tmp/tmpy3tktq8d']
[2022-02-10 16:31:47,932] {standard_task_runner.py:77} INFO - Job 932: Subtask local_to_gcs_task
[2022-02-10 16:31:48,162] {logging_mixin.py:109} INFO - Running <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2019-03-01T00:00:00+00:00 [running]> on host 106a34111faf
[2022-02-10 16:31:48,289] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-10 16:31:48,382] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ex_1_data_ingestion_gcs_dag_v3
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2019-03-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-03-01T00:00:00+00:00
[2022-02-10 16:33:18,433] {python.py:175} INFO - Done. Returned value was: None
[2022-02-10 16:33:18,520] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ex_1_data_ingestion_gcs_dag_v3, task_id=local_to_gcs_task, execution_date=20190301T000000, start_date=20220210T163147, end_date=20220210T163318
[2022-02-10 16:33:18,613] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-10 16:33:18,676] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
