[2022-02-02 20:41:35,619] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2019-11-01T00:00:00+00:00 [queued]>
[2022-02-02 20:41:35,633] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2019-11-01T00:00:00+00:00 [queued]>
[2022-02-02 20:41:35,635] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-02 20:41:35,635] {taskinstance.py:1239} INFO - Starting attempt 2 of 2
[2022-02-02 20:41:35,636] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-02 20:41:35,654] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2019-11-01 00:00:00+00:00
[2022-02-02 20:41:35,662] {standard_task_runner.py:52} INFO - Started process 15966 to run task
[2022-02-02 20:41:35,675] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ex_1_data_ingestion_gcs_dag_v3', 'local_to_gcs_task', 'scheduled__2019-11-01T00:00:00+00:00', '--job-id', '414', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_hw_1_ex.py', '--cfg-path', '/tmp/tmp115drww6', '--error-file', '/tmp/tmpfgvlr13p']
[2022-02-02 20:41:35,677] {standard_task_runner.py:77} INFO - Job 414: Subtask local_to_gcs_task
[2022-02-02 20:41:35,768] {logging_mixin.py:109} INFO - Running <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2019-11-01T00:00:00+00:00 [running]> on host 700aeb16bae0
[2022-02-02 20:41:35,831] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-02 20:41:35,869] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ex_1_data_ingestion_gcs_dag_v3
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2019-11-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-11-01T00:00:00+00:00
[2022-02-02 20:41:48,243] {python.py:175} INFO - Done. Returned value was: None
[2022-02-02 20:41:48,264] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ex_1_data_ingestion_gcs_dag_v3, task_id=local_to_gcs_task, execution_date=20191101T000000, start_date=20220202T204135, end_date=20220202T204148
[2022-02-02 20:41:48,313] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-02 20:41:48,355] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-02-10 16:54:10,258] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2019-11-01T00:00:00+00:00 [queued]>
[2022-02-10 16:54:10,274] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2019-11-01T00:00:00+00:00 [queued]>
[2022-02-10 16:54:10,275] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-10 16:54:10,276] {taskinstance.py:1239} INFO - Starting attempt 2 of 2
[2022-02-10 16:54:10,277] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-10 16:54:10,291] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2019-11-01 00:00:00+00:00
[2022-02-10 16:54:10,309] {standard_task_runner.py:52} INFO - Started process 1537 to run task
[2022-02-10 16:54:10,320] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ex_1_data_ingestion_gcs_dag_v3', 'local_to_gcs_task', 'scheduled__2019-11-01T00:00:00+00:00', '--job-id', '1015', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_hw_1_ex.py', '--cfg-path', '/tmp/tmpqgmcmcxs', '--error-file', '/tmp/tmpbq1kjgf3']
[2022-02-10 16:54:10,327] {standard_task_runner.py:77} INFO - Job 1015: Subtask local_to_gcs_task
[2022-02-10 16:54:10,461] {logging_mixin.py:109} INFO - Running <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2019-11-01T00:00:00+00:00 [running]> on host 106a34111faf
[2022-02-10 16:54:10,555] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-10 16:54:10,601] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ex_1_data_ingestion_gcs_dag_v3
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2019-11-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-11-01T00:00:00+00:00
[2022-02-10 16:55:11,594] {python.py:175} INFO - Done. Returned value was: None
[2022-02-10 16:55:11,622] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ex_1_data_ingestion_gcs_dag_v3, task_id=local_to_gcs_task, execution_date=20191101T000000, start_date=20220210T165410, end_date=20220210T165511
[2022-02-10 16:55:11,664] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-10 16:55:11,715] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
