[2022-02-02 19:12:47,838] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2021-09-01T00:00:00+00:00 [queued]>
[2022-02-02 19:12:47,854] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2021-09-01T00:00:00+00:00 [queued]>
[2022-02-02 19:12:47,855] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-02 19:12:47,856] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-02 19:12:47,857] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-02 19:12:47,874] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2021-09-01 00:00:00+00:00
[2022-02-02 19:12:47,885] {standard_task_runner.py:52} INFO - Started process 11883 to run task
[2022-02-02 19:12:47,899] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ex_1_data_ingestion_gcs_dag_v3', 'local_to_gcs_task', 'scheduled__2021-09-01T00:00:00+00:00', '--job-id', '400', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_hw_1_ex.py', '--cfg-path', '/tmp/tmphziwfofs', '--error-file', '/tmp/tmpxc14_812']
[2022-02-02 19:12:47,902] {standard_task_runner.py:77} INFO - Job 400: Subtask local_to_gcs_task
[2022-02-02 19:12:48,017] {logging_mixin.py:109} INFO - Running <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2021-09-01T00:00:00+00:00 [running]> on host 700aeb16bae0
[2022-02-02 19:12:48,069] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-02 19:12:48,103] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ex_1_data_ingestion_gcs_dag_v3
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2021-09-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-09-01T00:00:00+00:00
[2022-02-02 19:12:48,429] {python.py:175} INFO - Done. Returned value was: None
[2022-02-02 19:12:48,450] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ex_1_data_ingestion_gcs_dag_v3, task_id=local_to_gcs_task, execution_date=20210901T000000, start_date=20220202T191247, end_date=20220202T191248
[2022-02-02 19:12:48,515] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-02 19:12:48,571] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-02-10 14:54:40,649] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2021-09-01T00:00:00+00:00 [queued]>
[2022-02-10 14:54:40,689] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2021-09-01T00:00:00+00:00 [queued]>
[2022-02-10 14:54:40,702] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-10 14:54:40,707] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-10 14:54:40,717] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-10 14:54:40,745] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2021-09-01 00:00:00+00:00
[2022-02-10 14:54:40,759] {standard_task_runner.py:52} INFO - Started process 3552 to run task
[2022-02-10 14:54:40,769] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ex_1_data_ingestion_gcs_dag_v3', 'local_to_gcs_task', 'scheduled__2021-09-01T00:00:00+00:00', '--job-id', '754', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_hw_1_ex.py', '--cfg-path', '/tmp/tmplyl3d2kb', '--error-file', '/tmp/tmpukeydd1m']
[2022-02-10 14:54:40,774] {standard_task_runner.py:77} INFO - Job 754: Subtask local_to_gcs_task
[2022-02-10 14:54:40,941] {logging_mixin.py:109} INFO - Running <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2021-09-01T00:00:00+00:00 [running]> on host e30f201fae61
[2022-02-10 14:54:41,044] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-10 14:54:41,090] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ex_1_data_ingestion_gcs_dag_v3
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2021-09-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-09-01T00:00:00+00:00
[2022-02-10 14:54:41,496] {python.py:175} INFO - Done. Returned value was: None
[2022-02-10 14:54:41,541] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ex_1_data_ingestion_gcs_dag_v3, task_id=local_to_gcs_task, execution_date=20210901T000000, start_date=20220210T145440, end_date=20220210T145441
[2022-02-10 14:54:41,685] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-10 14:54:41,774] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-02-10 15:42:50,244] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2021-09-01T00:00:00+00:00 [queued]>
[2022-02-10 15:42:50,274] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2021-09-01T00:00:00+00:00 [queued]>
[2022-02-10 15:42:50,276] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-10 15:42:50,278] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-10 15:42:50,279] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-10 15:42:50,305] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2021-09-01 00:00:00+00:00
[2022-02-10 15:42:50,317] {standard_task_runner.py:52} INFO - Started process 1208 to run task
[2022-02-10 15:42:50,330] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ex_1_data_ingestion_gcs_dag_v3', 'local_to_gcs_task', 'scheduled__2021-09-01T00:00:00+00:00', '--job-id', '879', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_hw_1_ex.py', '--cfg-path', '/tmp/tmpp578a1oc', '--error-file', '/tmp/tmp69ia5f8k']
[2022-02-10 15:42:50,335] {standard_task_runner.py:77} INFO - Job 879: Subtask local_to_gcs_task
[2022-02-10 15:42:50,599] {logging_mixin.py:109} INFO - Running <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2021-09-01T00:00:00+00:00 [running]> on host 276a0ad90304
[2022-02-10 15:42:50,690] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-10 15:42:50,755] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ex_1_data_ingestion_gcs_dag_v3
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2021-09-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-09-01T00:00:00+00:00
[2022-02-10 15:43:00,378] {python.py:175} INFO - Done. Returned value was: None
[2022-02-10 15:43:00,414] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ex_1_data_ingestion_gcs_dag_v3, task_id=local_to_gcs_task, execution_date=20210901T000000, start_date=20220210T154250, end_date=20220210T154300
[2022-02-10 15:43:00,516] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-10 15:43:00,575] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-02-10 16:45:24,276] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2021-09-01T00:00:00+00:00 [queued]>
[2022-02-10 16:45:24,313] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2021-09-01T00:00:00+00:00 [queued]>
[2022-02-10 16:45:24,315] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-10 16:45:24,317] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-10 16:45:24,319] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-10 16:45:24,353] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2021-09-01 00:00:00+00:00
[2022-02-10 16:45:24,372] {standard_task_runner.py:52} INFO - Started process 1065 to run task
[2022-02-10 16:45:24,388] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ex_1_data_ingestion_gcs_dag_v3', 'local_to_gcs_task', 'scheduled__2021-09-01T00:00:00+00:00', '--job-id', '991', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_hw_1_ex.py', '--cfg-path', '/tmp/tmpoqvwrvih', '--error-file', '/tmp/tmpi484i_o6']
[2022-02-10 16:45:24,392] {standard_task_runner.py:77} INFO - Job 991: Subtask local_to_gcs_task
[2022-02-10 16:45:24,505] {logging_mixin.py:109} INFO - Running <TaskInstance: ex_1_data_ingestion_gcs_dag_v3.local_to_gcs_task scheduled__2021-09-01T00:00:00+00:00 [running]> on host 106a34111faf
[2022-02-10 16:45:24,560] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-10 16:45:24,594] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ex_1_data_ingestion_gcs_dag_v3
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2021-09-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-09-01T00:00:00+00:00
[2022-02-10 16:45:25,012] {python.py:175} INFO - Done. Returned value was: None
[2022-02-10 16:45:25,056] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ex_1_data_ingestion_gcs_dag_v3, task_id=local_to_gcs_task, execution_date=20210901T000000, start_date=20220210T164524, end_date=20220210T164525
[2022-02-10 16:45:25,128] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-10 16:45:25,234] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
